CREATE TABLE all_notes (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           note TEXT NOT NULL,
                           completed BOOLEAN DEFAULT FALSE,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
